title: Nereon
description: >-
  Universal configuration model, schema and syntax
  for processes, containers and more.
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

includes_dir: '.'

tagline: >-
  Consolidated configuration<br>for every process and container

pitch: >-
  Because the configuration expectations of your software
  deserve to be managed consistently.

landing_priority: [specs, software, blog]

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc/nereon

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/specs/nereon-syntax/", title: "Read the Specs" }
  - { url: "/software/", title: "See the Ecosystem" }

permalink: /blog/:month-:day-:year/:title/

collections:
  software:
    output: true
    permalink: /software/:path/
  pages:
    output: true
    permalink: /:name/
  specs:
    output: false
    permalink: /specs/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

url: "https://nereon.com/"
github_repo_url: "https://github.com/nereon/nereon.com"


tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"
